[package]
name = "evnet"
version = "0.1.0-rc3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An event driven peer to peer networking plugin for bevy built ontop of bevy_matchbox and webrtc"
repository = "https://github.com/MalekiRe/evnet"

[dependencies]
bevy = "0.15.1"
bevy_matchbox = "0.11.0"
futures = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
bincode = "1.3.3"